# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/lab2_code_for_cadets_2026/Lab2.xdc

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_microblaze_0_0/design_1_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_microblaze_0_0 || ORIG_REF_NAME==design_1_microblaze_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_dlmb_v10_0/design_1_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_dlmb_v10_0 || ORIG_REF_NAME==design_1_dlmb_v10_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ilmb_v10_0/design_1_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_ilmb_v10_0 || ORIG_REF_NAME==design_1_ilmb_v10_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_dlmb_bram_if_cntlr_0/design_1_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==design_1_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ilmb_bram_if_cntlr_0/design_1_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==design_1_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_lmb_bram_0/design_1_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_lmb_bram_0 || ORIG_REF_NAME==design_1_lmb_bram_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_mdm_1_0/design_1_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_mdm_1_0 || ORIG_REF_NAME==design_1_mdm_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_clk_wiz_1_0/design_1_clk_wiz_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_1_0 || ORIG_REF_NAME==design_1_clk_wiz_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_rst_clk_wiz_1_100M_0/design_1_rst_clk_wiz_1_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==design_1_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_uartlite_0_0/design_1_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_uartlite_0_0 || ORIG_REF_NAME==design_1_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_smc_0/design_1_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_smc_0 || ORIG_REF_NAME==design_1_axi_smc_0} -quiet] -quiet

# Block Designs: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/bd_afc3.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_0/bd_afc3_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_1/bd_afc3_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_2/bd_afc3_arinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_3/bd_afc3_rinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_4/bd_afc3_awinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_5/bd_afc3_winsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_6/bd_afc3_binsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_7/bd_afc3_aroutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_8/bd_afc3_routsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_9/bd_afc3_awoutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_10/bd_afc3_woutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_11/bd_afc3_boutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_12/bd_afc3_arni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_13/bd_afc3_rni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_14/bd_afc3_awni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_15/bd_afc3_wni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_16/bd_afc3_bni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_17/bd_afc3_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_18/bd_afc3_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_19/bd_afc3_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_20/bd_afc3_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_21/bd_afc3_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_22/bd_afc3_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_23/bd_afc3_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_24/bd_afc3_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_25/bd_afc3_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_26/bd_afc3_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_27/bd_afc3_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_28/bd_afc3_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_29/bd_afc3_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_30/bd_afc3_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_31/bd_afc3_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_32/bd_afc3_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_33/bd_afc3_m01s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_34/bd_afc3_m01arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_35/bd_afc3_m01rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_36/bd_afc3_m01awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_37/bd_afc3_m01wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_38/bd_afc3_m01bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_39/bd_afc3_m01e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_mig_7series_0_0/design_1_mig_7series_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_mig_7series_0_0 || ORIG_REF_NAME==design_1_mig_7series_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_smc_1_0/design_1_axi_smc_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_smc_1_0 || ORIG_REF_NAME==design_1_axi_smc_1_0} -quiet] -quiet

# Block Designs: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_0/bd_0/bd_a878.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_0/bd_a878_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_1/bd_a878_psr0_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_2/bd_a878_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_3/bd_a878_psr_aclk1_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_4/bd_a878_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_5/bd_a878_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_6/bd_a878_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_7/bd_a878_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_8/bd_a878_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_9/bd_a878_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_10/bd_a878_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_11/bd_a878_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_12/bd_a878_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_13/bd_a878_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_14/bd_a878_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_15/bd_a878_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_16/bd_a878_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_17/bd_a878_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_18/bd_a878_s01mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_19/bd_a878_s01tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_20/bd_a878_s01sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_21/bd_a878_s01a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_22/bd_a878_sarn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_23/bd_a878_srn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_24/bd_a878_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_25/bd_a878_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_26/bd_a878_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_27/bd_a878_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_28/bd_a878_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_29/bd_a878_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_30/bd_a878_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_rst_mig_7series_0_100M_0/design_1_rst_mig_7series_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_rst_mig_7series_0_100M_0 || ORIG_REF_NAME==design_1_rst_mig_7series_0_100M_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_My_Lab2_0_3/design_1_My_Lab2_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_My_Lab2_0_3 || ORIG_REF_NAME==design_1_My_Lab2_0_3} -quiet] -quiet

# IP: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_My_Lab2_0_3/src/clk_wiz_1_4/clk_wiz_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk_wiz_1 || ORIG_REF_NAME==clk_wiz_1} -quiet] -quiet

# IP: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_My_Lab2_0_3/src/clk_wiz_0_4/clk_wiz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] -quiet

# XDC: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_microblaze_0_0/design_1_microblaze_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_microblaze_0_0 || ORIG_REF_NAME==design_1_microblaze_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_microblaze_0_0/design_1_microblaze_0_0_ooc_debug.xdc

# XDC: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_lmb_bram_0/design_1_lmb_bram_0_ooc.xdc

# XDC: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_mdm_1_0/design_1_mdm_1_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_mdm_1_0 || ORIG_REF_NAME==design_1_mdm_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_mdm_1_0/design_1_mdm_1_0_ooc_trace.xdc

# XDC: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_clk_wiz_1_0/design_1_clk_wiz_1_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_1_0 || ORIG_REF_NAME==design_1_clk_wiz_1_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_clk_wiz_1_0/design_1_clk_wiz_1_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_1_0 || ORIG_REF_NAME==design_1_clk_wiz_1_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_clk_wiz_1_0/design_1_clk_wiz_1_0_ooc.xdc

# XDC: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_rst_clk_wiz_1_100M_0/design_1_rst_clk_wiz_1_100M_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==design_1_rst_clk_wiz_1_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_rst_clk_wiz_1_100M_0/design_1_rst_clk_wiz_1_100M_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==design_1_rst_clk_wiz_1_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_axi_uartlite_0_0/design_1_axi_uartlite_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_axi_uartlite_0_0 || ORIG_REF_NAME==design_1_axi_uartlite_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_axi_uartlite_0_0/design_1_axi_uartlite_0_0_ooc.xdc

# XDC: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_axi_uartlite_0_0/design_1_axi_uartlite_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_axi_uartlite_0_0 || ORIG_REF_NAME==design_1_axi_uartlite_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_1/bd_afc3_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_1/bd_afc3_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_2/bd_afc3_arinsw_0_ooc.xdc

# XDC: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_3/bd_afc3_rinsw_0_ooc.xdc

# XDC: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_4/bd_afc3_awinsw_0_ooc.xdc

# XDC: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_5/bd_afc3_winsw_0_ooc.xdc

# XDC: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_6/bd_afc3_binsw_0_ooc.xdc

# XDC: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_7/bd_afc3_aroutsw_0_ooc.xdc

# XDC: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_8/bd_afc3_routsw_0_ooc.xdc

# XDC: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_9/bd_afc3_awoutsw_0_ooc.xdc

# XDC: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_10/bd_afc3_woutsw_0_ooc.xdc

# XDC: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_11/bd_afc3_boutsw_0_ooc.xdc

# XDC: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_12/bd_afc3_arni_0_ooc.xdc

# XDC: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_13/bd_afc3_rni_0_ooc.xdc

# XDC: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_14/bd_afc3_awni_0_ooc.xdc

# XDC: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_15/bd_afc3_wni_0_ooc.xdc

# XDC: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_16/bd_afc3_bni_0_ooc.xdc

# XDC: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_20/bd_afc3_s00a2s_0_ooc.xdc

# XDC: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_21/bd_afc3_sarn_0_ooc.xdc

# XDC: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_22/bd_afc3_srn_0_ooc.xdc

# XDC: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_23/bd_afc3_sawn_0_ooc.xdc

# XDC: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_24/bd_afc3_swn_0_ooc.xdc

# XDC: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_25/bd_afc3_sbn_0_ooc.xdc

# XDC: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_26/bd_afc3_m00s2a_0_ooc.xdc

# XDC: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_27/bd_afc3_m00arn_0_ooc.xdc

# XDC: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_28/bd_afc3_m00rn_0_ooc.xdc

# XDC: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_29/bd_afc3_m00awn_0_ooc.xdc

# XDC: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_30/bd_afc3_m00wn_0_ooc.xdc

# XDC: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_31/bd_afc3_m00bn_0_ooc.xdc

# XDC: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_33/bd_afc3_m01s2a_0_ooc.xdc

# XDC: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_34/bd_afc3_m01arn_0_ooc.xdc

# XDC: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_35/bd_afc3_m01rn_0_ooc.xdc

# XDC: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_36/bd_afc3_m01awn_0_ooc.xdc

# XDC: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_37/bd_afc3_m01wn_0_ooc.xdc

# XDC: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_38/bd_afc3_m01bn_0_ooc.xdc

# XDC: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/ooc.xdc

# XDC: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/smartconnect.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_axi_smc_0 || ORIG_REF_NAME==design_1_axi_smc_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_mig_7series_0_0/design_1_mig_7series_0_0/user_design/constraints/design_1_mig_7series_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_mig_7series_0_0 || ORIG_REF_NAME==design_1_mig_7series_0_0} -quiet] -quiet

# XDC: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_mig_7series_0_0/design_1_mig_7series_0_0/user_design/constraints/design_1_mig_7series_0_0_ooc.xdc

# XDC: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_mig_7series_0_0/design_1_mig_7series_0_0_board.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_mig_7series_0_0 || ORIG_REF_NAME==design_1_mig_7series_0_0} -quiet] -quiet

# XDC: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_1/bd_a878_psr0_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_1/bd_a878_psr0_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_2/bd_a878_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_2/bd_a878_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_3/bd_a878_psr_aclk1_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_3/bd_a878_psr_aclk1_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_4/bd_a878_arsw_0_ooc.xdc

# XDC: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_5/bd_a878_rsw_0_ooc.xdc

# XDC: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_6/bd_a878_awsw_0_ooc.xdc

# XDC: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_7/bd_a878_wsw_0_ooc.xdc

# XDC: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_8/bd_a878_bsw_0_ooc.xdc

# XDC: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_12/bd_a878_s00a2s_0_ooc.xdc

# XDC: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_13/bd_a878_sarn_0_ooc.xdc

# XDC: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_14/bd_a878_srn_0_ooc.xdc

# XDC: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_15/bd_a878_sawn_0_ooc.xdc

# XDC: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_16/bd_a878_swn_0_ooc.xdc

# XDC: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_17/bd_a878_sbn_0_ooc.xdc

# XDC: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_21/bd_a878_s01a2s_0_ooc.xdc

# XDC: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_22/bd_a878_sarn_1_ooc.xdc

# XDC: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_23/bd_a878_srn_1_ooc.xdc

# XDC: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_24/bd_a878_m00s2a_0_ooc.xdc

# XDC: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_25/bd_a878_m00arn_0_ooc.xdc

# XDC: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_26/bd_a878_m00rn_0_ooc.xdc

# XDC: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_27/bd_a878_m00awn_0_ooc.xdc

# XDC: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_28/bd_a878_m00wn_0_ooc.xdc

# XDC: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_29/bd_a878_m00bn_0_ooc.xdc

# XDC: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_0/ooc.xdc

# XDC: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_0/smartconnect.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_axi_smc_1_0 || ORIG_REF_NAME==design_1_axi_smc_1_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_rst_mig_7series_0_100M_0/design_1_rst_mig_7series_0_100M_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_rst_mig_7series_0_100M_0 || ORIG_REF_NAME==design_1_rst_mig_7series_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_rst_mig_7series_0_100M_0/design_1_rst_mig_7series_0_100M_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_rst_mig_7series_0_100M_0 || ORIG_REF_NAME==design_1_rst_mig_7series_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_My_Lab2_0_3/src/clk_wiz_1_4/clk_wiz_1.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz_1 || ORIG_REF_NAME==clk_wiz_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_My_Lab2_0_3/src/clk_wiz_1_4/clk_wiz_1_ooc.xdc

# XDC: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_My_Lab2_0_3/src/clk_wiz_0_4/clk_wiz_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/ip/design_1_My_Lab2_0_3/src/clk_wiz_0_4/clk_wiz_0_ooc.xdc

# XDC: c:/Users/C27Mohamed.Metwally/ece383_wksp/lab3/Lab3.gen/sources_1/bd/design_1/design_1_ooc.xdc
